### ISSUE TITLE
adding a separator / terminator character for a TCP JSONRPC protocol  

### ISSUE THREAD

**Issue by PiRK** [karyontech/karyon#9]
Hi. I'm trying to use the lib to implement an existing  JSON-RPC protocol which ends each JSON response with newline "\n" character. 
Is this possible with this lib?

So far I only managed to get JSON RPC responses without separator. This makes it inconvenient for the client to know when the response has been received completely without some complex and expensive heuristics such as counting the number of opening and closing braces, or just trying to parse the JSON data, fail, read another chunk of data from the socket, try again... etc
For my use case the data size and number of JSON fields of the response can be quite large, I already found out that the solution of trying to parse until it succeeds is not realistically going to work. Counting the braces to find out when the JSON data is complete seems workable, but it still adds a significant drag vs just checking if a "\n" is present in my buffer.

**Comment by hozan23** [comment]
Hello @PiRK,  

I think the solution is to create a new custom codec, similar to the existing JSON [codec](https://github.com/karyontech/karyon/blob/master/jsonrpc/src/codec.rs#L15-L47), and use it as the default codec for both the [server](https://github.com/karyontech/karyon/blob/master/jsonrpc/src/server/mod.rs#L367) and the [client](https://github.com/karyontech/karyon/blob/master/jsonrpc/src/client/mod.rs#L208).  

Currently, there is no way to pass a custom codec. However, we could modify the builder API to allow specifying the codec when building the client and the server.
